language: java
jdk:
- oraclejdk8
if: tag IS blank AND type != pull_request
before_install:
- openssl aes-256-cbc -k "$keyStoreEncryptionKey" -in keystore.jks.enc -out keystore.jks
  -d
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
notifications:
  email: false
before_script: source setup_environment.sh
script:
- "./gradlew build --continue --stacktrace"
addons:
  apt:
    packages:
    - oracle-java8-installer
before_deploy:
- cd $TRAVIS_BUILD_DIR
- "./prepare_deploy.sh"
env:
  global:
  - blKeyStoreFingerprint=38:06:7D:68:78:81:1E:FB:38:B6:A0:45:52:1C:FD:80:B9:B6:0B:38
  - blKeyStoreAlias=Angry-Pixel
  - secure: dHYC2zn0pIpFZyw5sxNNak3DP0vPd0JGTXSTFBxPGlsvFNZNm7r3cbdsKiOQpwdm+i07cuw7T8CajCcgyAuzCUx3UbEoaJHkGW6VmbJ3vBsgpEHgDykcxgIESfunqRvocI/KW8NmGENza0hl6ja2rIEiQNIteEOyj7aWyajUKVMfGRzX1ABw179AOVs+giBstEcj5VxMGh9JPnk53PHw1Yr2bAXexm17G5vjgu0FMbQpMYZwHmtOT6EwGQ0lzDS+p62ECzY7pCzYQWv1cTH3c6BVdckT7uqP/qe110ER/RSUc9rCosiIXvEZaI/lUCq9qY8KePOGbTR3o0OefOCv3w9LT1y23yAwTTIKhs1E4reiRgTRKrXV0kfCEygSalrw9rZ/AgH6Rj1qW/Vxtx6xKbs4DqHJ0egwdSe71b16iPDVcK0617lPp4CO5Y8XvJSLmceeBWJzfcfsL0GiIBVj9FxZzwvSySiBxoS7SevF69uICyP2iG8mqK0dgYvSQa5pu+dSWJDDRTRzzI/bLNP2cJzCBBCk5WwSzxiW3Q5xeOFJ00F73lj5vEOdAkEetfahMQW0xUWKWlj0ZqbgV9Dr9mVuE6Lhmv2cp2g4mmQTZ0xNK+VuiqvB+ySrfXNv4xkdVBWyzr/sV+PhR3kBAUuLSrYQ4d8uQizQXlLYGE3DSiE=
  - secure: dXzNtsBJkwKoBT5WxMqUu3qcA8nWChO39HwMPSzp2LqFrKM829GxaByxcOtI3RYT5ZQK3htJ0rxDRHecj0w5Q+XrhJWvTEW5DJoPAvSI1idfOunfAjMe1VkTxiwgtjSgBh2kQ9Fb8p4ot9TAa2MJjU5zxvP1uyXqx9k3y1AYi/NwmagSPG7ohWoCU0kWQnO9K4cmiWxuTBcywtvpNDROxu8NHyHstXFLedG+0arUZCe+NX5zZRyKu7FNh+Ld0/8gZ7KJcwb2/zKWWmzZ3VqP92EYUEIUf71Rz3y4ECRWQlnJpdXpwiZKAA7xLxQt8eZfbokcYoGrlOvmzFSzKb34o+YYr0sKX0S5wZndKouYDBispHMNDDJvd5fyq94N0YSRvp8w+IV7yYEflLhCcGMkrw0Pyi1ckpJ/WCd1eP8h45EfH9osZAqDl+Bcw2YCWWYT4Xqyngg/iG1FVmMB4XTJrnQFeTL4g07g242JuTI9YTxN2yDa4s1EHDeA/udZRE5h2nI+uScGweq4zuAsyjmNarCp9evyKnIVgq4EA5h6G7d6KfzWIzjeYanUYwmgIlvylot7fwMRJE2EdMTmiK2T+eG81MnrIkalpQA5eCTS3zXlOslscQSdL1okcEmKrbA4oNyzQxxw7JS7JFMvFkodRw8S8IJoDi8GCh7z/O0d/io=
  - secure: tXbMfPxcT2QfsGacX9Za8oz3g/pRRr+F8bVGvYazsGBjMdurylBIaLtYKt6fF6ZycWaewSarJWeHUzlDkTxWeXyKDrDEC2RTFAdCjUqOvbGt65iIPv7Z4dDE9TnT4sk90Ui9DMOm8bGllFG9SyXDqGimCxJ8lg4Z7ICMCEtkBc3EHHp20ACIUtUcs1qefizOUt/pAKL2RlC9ZOISczpgK3yGd3nmwA9kTOhgpErdUvqa5W6F0GjwwxpFOJGffi87cCUTah+M/5vjEh8SCR6EwzleLkxoi/MfEvs1Qhmv4E5nOpTM2Eb9NpoUa359ME80DK+vsMUB/TBVYWi4QIG5i4j9Zax4PhMUbHyFNmPLQxcLK+wsL8V3NdNvtWXiNnywyqbh0D2cCht820315Ff/+uMw/NAqgAkBDB+Zezagw5E32BxbCJZYvLMsApuShAlhVyBNCT9kW/UkQN/hy3o9l1Okl7vyaHIi6tI2Nt5vRzdqzf90zjIk2TQGuGMpvjSI7hNs6Oa36ST9CdcX4457P2nfqTH7QvXegW/YskvYUZZzWW+mZyz7Pz0qRuWVsihFR01gNuhwUt7/K3SeB7MUxW8yWZA6nxLLZ1vDM1kPls8wzlfEFxOAMaOBon/2prJGYXGB/ThTsTEpcFohyJqput84Ygkeo5ffKkLZJEw0ZHE=
deploy:
- provider: releases
  prerelease: true
  api_key:
    secure: ScVxjPfCeKdADnYTOPmIsfVrEKxTDIRzXrYeuPEHx1UMa3APIOF52GbvVerHA9t6Xq+wC0QiqDJvum9LPoesZUh9FD4tYzTHd/qjr2D1o3Mzb5WngJcKJCqY2aHv5Ok8dIQjRo1L5vJ952X2d1Fz1omnh8cO4yiSyxOEzp5qDkiQeQk0uuTRWh2KxA4uYh3qocK+kVSZ17uwVyrIwq30XUeJKYhHUv/yFOWAMooueeiM7tn+HXYaybxNbWAKE4uNsFHK3l/y2oJ9DLy+oGpDBIF5LdVS91CCmCDOqyY1aHL7+JcOo8e1B3GaHMoO3w1jeIEzm0pS5lTWCbGOkYwQ0j3bu6DI5RS4hD2y+gv4S4FA6BYhOU02XoWVIMPMvDY6RxT0FHvTZPXmmHIRKHtcO6Kf0J0ELgxuS1QqBySaJLnQiWduZ9j6mOV+XKyEeJC99ls/WZu6usip72gqNOGvIYTLQYb4f08GoeJGpAwXJYLmXOX0IMYC53Z9ih6j74dSu/Lx2VhK2ZZpPt+9KXnSYqD2bhkhN1W3Makp7DtUB3v8oJWN+McVc6uN7DqysqJzv4BKC6e5M/ayzblun0gSv0dAozDl5zGNdQQqgrRJOKcUZLCslIMYcfoWO2j5PJLw1oj/hz6VKiEE3jKxcWYF8aR7Rw2twYRl4tKWOBJROfo=
  name: "$DEPLOY_BUILD_TITLE"
  body: "$DEPLOY_BUILD_BODY"
  file_glob: true
  file:
  - "$DEPLOY_REPOSITORY_DIR_NAME/build/libs/TheBetweenlands-*-${DEPLOY_BUILD_NUMBER}-server.jar"
  - "$DEPLOY_REPOSITORY_DIR_NAME/build/libs/TheBetweenlands-*-${DEPLOY_BUILD_NUMBER}-universal.jar"
  skip_cleanup: true
  on:
    repo: Angry-Pixel/The-Betweenlands-Development-Builds
    condition: $DEPLOY_BUILD_TYPE = "development"
- provider: releases
  api_key:
    secure: ScVxjPfCeKdADnYTOPmIsfVrEKxTDIRzXrYeuPEHx1UMa3APIOF52GbvVerHA9t6Xq+wC0QiqDJvum9LPoesZUh9FD4tYzTHd/qjr2D1o3Mzb5WngJcKJCqY2aHv5Ok8dIQjRo1L5vJ952X2d1Fz1omnh8cO4yiSyxOEzp5qDkiQeQk0uuTRWh2KxA4uYh3qocK+kVSZ17uwVyrIwq30XUeJKYhHUv/yFOWAMooueeiM7tn+HXYaybxNbWAKE4uNsFHK3l/y2oJ9DLy+oGpDBIF5LdVS91CCmCDOqyY1aHL7+JcOo8e1B3GaHMoO3w1jeIEzm0pS5lTWCbGOkYwQ0j3bu6DI5RS4hD2y+gv4S4FA6BYhOU02XoWVIMPMvDY6RxT0FHvTZPXmmHIRKHtcO6Kf0J0ELgxuS1QqBySaJLnQiWduZ9j6mOV+XKyEeJC99ls/WZu6usip72gqNOGvIYTLQYb4f08GoeJGpAwXJYLmXOX0IMYC53Z9ih6j74dSu/Lx2VhK2ZZpPt+9KXnSYqD2bhkhN1W3Makp7DtUB3v8oJWN+McVc6uN7DqysqJzv4BKC6e5M/ayzblun0gSv0dAozDl5zGNdQQqgrRJOKcUZLCslIMYcfoWO2j5PJLw1oj/hz6VKiEE3jKxcWYF8aR7Rw2twYRl4tKWOBJROfo=
  name: "$DEPLOY_BUILD_TITLE"
  body: "$DEPLOY_BUILD_BODY"
  file_glob: true
  file:
  - "$DEPLOY_REPOSITORY_DIR_NAME/build/libs/TheBetweenlands-*-server.jar"
  - "$DEPLOY_REPOSITORY_DIR_NAME/build/libs/TheBetweenlands-*-universal.jar"
  skip_cleanup: true
  on:
    repo: Angry-Pixel/The-Betweenlands-Development-Builds
    condition: $DEPLOY_BUILD_TYPE = "release"
